### ISSUE TITLE
[Fix] Responsiveness of Latest Community News Section

### ISSUE THREAD

**Issue by itsmanojthapa** [RocketChat/RC4Community#205]
issue:
  1) image is bigger then content-box
  2) different size of content-box 

![image](https://user-images.githubusercontent.com/109368904/205421745-69dd0d30-a408-4a39-8d3b-8d52084aa16d.png)

**Comment by itsmanojthapa** [comment]
Assign me this issue

**Comment by Dnouv** [comment]
Hello @itsmanojthapa 

Thank you for reporting the issue. Please feel free to work on any issue by commenting, "I am currently working on this issue", there ain't any need to get assigned to work on issues. However, it would be nice of you if you could also let others know by commenting, "This issue is open for contributions" (in case you decide to no longer work on any issue).
Also, please add some more details to the issue; only adding an image is a bit confusing, and the texts are also friendly for screen-reader users.

Looking forward to your contributions. Thank you!
